name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
    - Casks/tokenration.rb

jobs:
  lint-test:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Check cask style
      run: brew style Casks/tokenration.rb

    - name: Install cask
      run: |
        brew tap MilosRandelovic/tokenration
        cp Casks/tokenration.rb "$(brew --repository MilosRandelovic/tokenration)/Casks/tokenration.rb"
        brew install --cask tokenration

    - name: Verify the app is installed
      run: test -d /Applications/TokenRation.app
